// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;
import java.io.InputStreamReader;
import edu.wpi.first.math.util.Units;



/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants. This class should not be used for any other purpose. All constants should be declared
 * globally (i.e. public static). Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public final class Constants {
  // Class generated by wpilib, not sure if needed
  //public static class OperatorConstants {

    /* We will figure out JSON parsing at a later time
    public static Gson gson = new Gson();
    public static JsonReader reader = new JsonReader(new InputStreamReader(getClass().getResourceAsStream("/src/main/deploy/swerve/modules/pidfproperties.json")));
    */

    // SWERVE MODULE MOTOR CREATION VALUES BELOW
    public static final boolean driveInverted = false;
    public static final int driveSmartCurrentLimit = 40;
    public static final double driveVoltageCompensation = 12.0;
    public static final double drivePotentialConversionFactor = Units.inchesToMeters(4 * Math.PI)/5.36; // Taken from the old constants file, most likely should change
    public static final double driveVelocityConversionFactor = Units.inchesToMeters(4 * Math.PI)/5.36/60; // This one too

    public static final boolean turnInverted = false;
    public static final int turnSmartCurrentLimit = 20;
    public static final double turnVoltageCompensation = 12.0;
    public static final double turnPotentialConversionFactor = 360/(12.8); // Taken from the old constants file as well
    public static final double turnVelocityConversionFactor = 0; // Not currently used

    // We just copied hard coded values from the JSON file "pidfproperties.json"
    public static final double pDriveMotor = 0.0020645;
    public static final double iDriveMotor = 0;
    public static final double dDriveMotor = 0;

    public static final double pTurnMotor = 0.0020645;
    public static final double iTurnMotor = 0;
    public static final double dTurnMotor = 0;

    public static final int canCoderAbsoluteSensorDiscontinuityPoint = 1;
    // END SWERVE MODULE MOTOR CREATION VALUES
  //}
}
