// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot;

import edu.wpi.first.math.util.Units;



/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants. This class should not be used for any other purpose. All constants should be declared
 * globally (i.e. public static). Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public final class Constants {
  // Class generated by wpilib, not sure if needed
  //public static class OperatorConstants {

    /* We will figure out JSON parsing at a later time
    public static Gson gson = new Gson();
    public static JsonReader reader = new JsonReader(new InputStreamReader(getClass().getResourceAsStream("/src/main/deploy/swerve/modules/pidfproperties.json")));
    */

    // SWERVE MODULE MOTOR CREATION VALUES BELOW
    public static final boolean driveInverted = false; 
    public static final int driveSmartCurrentLimit = 40;
    public static final double driveVoltageCompensation = 12.0;
    public static final double drivePotentialConversionFactor = Units.inchesToMeters(4 * Math.PI)/5.36; // Taken from the old constants file, most likely should change
    public static final double driveVelocityConversionFactor = Units.inchesToMeters(4 * Math.PI)/5.36/60; // This one too
    public static final double maxSpeed = 4.5; // Meters per second, taken from the old constants file as well
    public static final boolean turnInverted = false;
    public static final int turnSmartCurrentLimit = 20;
    public static final double turnVoltageCompensation = 12.0;
    public static final double turnPotentialConversionFactor = 360/(12.8); // Taken from the old constants file as well
    public static final double turnVelocityConversionFactor = 0; 

    // Used to set turnMotors to their offsets in order of canCoder ID's in order of 3, 6, 9, 12
    /*
    DEBUG
    Previously measured offsets: 3, 6, 9, 12
    Rotations: 0.218262, 0.861816, 0.290039, 0.332031
    Degrees: 78.57432, 310.25376, 104.41404, 119.53116
    Adjusted Degrees: 0, 231.67944, 25.83972, 40.95684

    Re-measured 2/21/2026:
    Rotations: 0.714844, 0.868164, 0.792480, 0.334473
    Degrees: 77.34384, 312.53904, 105.2928, 120.41028
    Adjusted Degrees: 0, 235.1952, 27.94896, 43.06644

     */
    // Rotation values from Pheonix tuner values {0.217285, 0.870361, 0.289307, 0.331543}
    public static final double turnOffsets[] = {78.2226, 313.32996, 104.15052, 119.35548};
    // We just copied hard coded values from the JSON file "pidfproperties.json"
    public static final double pDriveMotor = 0.0020645;
    public static final double iDriveMotor = 0;
    public static final double dDriveMotor = 0;

    public static final double pTurnMotor = 0.0035; // Increased to help deal with wheels not getting to their proper offsets
    public static final double iTurnMotor = 0;
    public static final double dTurnMotor = 0;

    public static final int canCoderAbsoluteSensorDiscontinuityPoint = 1;
    // END SWERVE MODULE MOTOR CREATION VALUES

    public static final boolean isOpenLoop = true;

    public static final double intakePivotLeftUpSetpoint = -1;
    public static final double intakePivotLeftDownSetpoint = -9.785757064819336;

    public static final double intakePivotRightUpSetpoint = 1.2;
    public static final double intakePivotRightDownSetpoint = 9.857186317443848;


    
  //}

/*

Max Speed LIST
Shoot Motors: 0.8
Feed Motor: 0.8
Index Motor: 0.6
Intake Spin Motor: 1


CanID LIST
CanID 1: Drive Motor (Front Left)
CanID 2: Turn Motor (Front Left)
CanID 3: CANCoder (Front Left)
CanID 4: Drive Motor (Front Right)
CanID 5: Turn Motor (Front Right)
CanID 6: CANCoder (Front Right)
CanID 7: Drive Motor (Back Right)
CanID 8: Turn Motor (Back Right)
CanID 9: CANCoder (Back Right)
CanID 10: Drive Motor (Back Left)
CanID 11: Turn Motor (Back Left)
CanID 12: CANCoder (Back Left)
CanID 13: PDH
CanID 14: CANdle
CanID 15: Climber [brake mode]
CanID 16: Spindexer [coast mode]
CanID 17: Feeder [coast mode]
CanID 18: Right Shooter [coast mode]
CanID 19: Left Shooter [coast mode]
CanID 20: Spin [coast mode] -- Intake
CanID 21: Intake Pivot Right [brake mode] -- Intake
CanID 22: Intake Pivot Left [brake mode] -- Intake
*/
}
